package uth.edu.vn.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import uth.edu.vn.entity.BaoCao;
import uth.edu.vn.entity.User;
import uth.edu.vn.enums.ReportType;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public interface BaoCaoRepository extends JpaRepository<BaoCao, Long> {
    
    /**
     * Find reports by type
     */
    List<BaoCao> findByType(ReportType type);
    
    /**
     * Find reports by type ordered by generation date descending
     */
    List<BaoCao> findByTypeOrderByGeneratedAtDesc(ReportType type);
    
    /**
     * Find reports generated by specific user
     */
    List<BaoCao> findByGeneratedBy(User user);
    
    /**
     * Find reports generated by user ID
     */
    List<BaoCao> findByGeneratedByIdOrderByGeneratedAtDesc(Long userId);
    
    /**
     * Find reports by generation date range
     */
    @Query("SELECT r FROM BaoCao r " +
           "WHERE r.generatedAt BETWEEN :startDate AND :endDate " +
           "ORDER BY r.generatedAt DESC")
    List<BaoCao> findByGeneratedAtBetween(@Param("startDate") LocalDateTime startDate, 
                                          @Param("endDate") LocalDateTime endDate);
    
    /**
     * Find reports by period date range
     */
    @Query("SELECT r FROM BaoCao r " +
           "WHERE r.periodStart >= :startDate " +
           "AND r.periodEnd <= :endDate " +
           "ORDER BY r.periodStart DESC")
    List<BaoCao> findByPeriodBetween(@Param("startDate") LocalDateTime startDate, 
                                     @Param("endDate") LocalDateTime endDate);
    
    /**
     * Find latest report by type
     */
    @Query("SELECT r FROM BaoCao r " +
           "WHERE r.type = :type " +
           "ORDER BY r.generatedAt DESC " +
           "LIMIT 1")
    Optional<BaoCao> findLatestByType(@Param("type") ReportType type);
    
    /**
     * Find reports by type and date range
     */
    @Query("SELECT r FROM BaoCao r " +
           "WHERE r.type = :type " +
           "AND r.generatedAt BETWEEN :startDate AND :endDate " +
           "ORDER BY r.generatedAt DESC")
    List<BaoCao> findByTypeAndDateRange(@Param("type") ReportType type, 
                                       @Param("startDate") LocalDateTime startDate, 
                                       @Param("endDate") LocalDateTime endDate);
    
    /**
     * Find monthly reports for specific year and month
     */
    @Query("SELECT r FROM BaoCao r " +
           "WHERE r.type = 'MONTHLY' " +
           "AND YEAR(r.periodStart) = :year " +
           "AND MONTH(r.periodStart) = :month " +
           "ORDER BY r.generatedAt DESC")
    List<BaoCao> findMonthlyReports(@Param("year") int year, 
                                    @Param("month") int month);
    
    /**
     * Find daily reports for specific date
     */
    @Query("SELECT r FROM BaoCao r " +
           "WHERE r.type = 'DAILY' " +
           "AND DATE(r.periodStart) = DATE(:date) " +
           "ORDER BY r.generatedAt DESC")
    List<BaoCao> findDailyReports(@Param("date") LocalDateTime date);
    
    /**
     * Count reports by type
     */
    Long countByType(ReportType type);
    
    /**
     * Count reports generated in date range
     */
    @Query("SELECT COUNT(r) FROM BaoCao r " +
           "WHERE r.generatedAt BETWEEN :startDate AND :endDate")
    Long countByDateRange(@Param("startDate") LocalDateTime startDate, 
                         @Param("endDate") LocalDateTime endDate);
    
    /**
     * Find recent reports with limit
     */
    @Query("SELECT r FROM BaoCao r " +
           "ORDER BY r.generatedAt DESC")
    List<BaoCao> findRecentReports(org.springframework.data.domain.Pageable pageable);
    
    /**
     * Find reports by title keyword
     */
    @Query("SELECT r FROM BaoCao r " +
           "WHERE LOWER(r.title) LIKE LOWER(CONCAT('%', :keyword, '%')) " +
           "ORDER BY r.generatedAt DESC")
    List<BaoCao> findByTitleContaining(@Param("keyword") String keyword);
    
    /**
     * Get report statistics by type
     */
    @Query("SELECT r.type, COUNT(r) " +
           "FROM BaoCao r " +
           "GROUP BY r.type " +
           "ORDER BY COUNT(r) DESC")
    List<Object[]> getReportStatistics();
}
